// Generated by CoffeeScript 1.5.0
(function() {
  var GlassMaterial, RenderJob, ScExporter, SunflowRenderer, THREE,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  THREE = window.THREE || {};

  THREE.SunflowRenderer = SunflowRenderer = (function() {

    function SunflowRenderer(options) {
      options = options || {};
      this.port = options.port || 3000;
      this.host = options.host || "localhost";
    }

    SunflowRenderer.prototype.render = function() {
      console.log("Render");
      return null;
    };

    return SunflowRenderer;

  })();

  ScExporter = (function() {

    function ScExporter() {}

    ScExporter.exportGeometry = function(scene) {
      return "";
    };

    ScExporter.exportShaders = function(scene) {
      return "";
    };

    ScExporter.exportInstances = function(scene) {
      return "";
    };

    return ScExporter;

  })();

  THREE.GlassMaterial = GlassMaterial = (function(_super) {

    __extends(GlassMaterial, _super);

    function GlassMaterial() {
      GlassMaterial.__super__.constructor.call(this);
    }

    GlassMaterial.prototype.test = function() {
      return null;
    };

    return GlassMaterial;

  })(THREE.Material);

  RenderJob = (function() {

    function RenderJob(scExport) {}

    RenderJob.prototype.test = function() {
      return null;
    };

    return RenderJob;

  })();

}).call(this);
